apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "chart.fullname" . }}-driver
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  attachRequired: true
  podInfoOnMount: false  # are we sure about this?
  volumeLifecycleModes:
    - Persistent
    - Ephemeral