apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
provisioner: csi-rclone
# TODO: check what it does
volumeBindingMode: Immediate
reclaimPolicy: Delete
parameters:
  csi.storage.k8s.io/provisioner-secret-name: rclone-provisioner-secret
  csi.storage.k8s.io/provisioner-secret-namespace: csi-rclone
  csi.storage.k8s.io/node-publish-secret-name: rclone-secret
  csi.storage.k8s.io/node-publish-secret-namespace: csi-rclone
