apiVersion: v1
kind: Secret
metadata:
  name: rclone-provisioner-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
# options and args for provisioner (mkdir and purge)
# do NOT put vfs and cache args here.
stringData:
  remote: "s3"
  remotePath: "projectname"
  s3-provider: "Minio"
  s3-endpoint: "http://minio.munio:9000"
  s3-access-key-id: "ACCESS_KEY_ID"
  s3-secret-access-key: "SECRET_ACCESS_KEY"
---
apiVersion: v1
kind: Secret
metadata:
  name: rclone-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
# options and args for mounting
# Put VFS and cache args here.
stringData:
  remote: "s3"
  remotePath: "projectname"
  vfs-cache-mode: "writes"
  s3-provider: "Minio"
  s3-endpoint: "http://minio.munio:9000"
  s3-access-key-id: "ACCESS_KEY_ID"
  s3-secret-access-key: "SECRET_ACCESS_KEY"